# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Server - Production dependencies
  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "weekly"
    requirements-file: "requirements.txt"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    groups:
      server-prod:
        patterns:
          - "*"

  # Server - Development dependencies
  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "weekly"
    requirements-file: "requirements-dev.txt"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(dev-deps)"
    groups:
      server-dev:
        patterns:
          - "*"

  # ETL - Production dependencies
  - package-ecosystem: "pip"
    directory: "/etl"
    schedule:
      interval: "weekly"
    requirements-file: "requirements.txt"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    groups:
      etl-prod:
        patterns:
          - "*"

  # ETL - Development dependencies
  - package-ecosystem: "pip"
    directory: "/etl"
    schedule:
      interval: "weekly"
    requirements-file: "requirements-dev.txt"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(dev-deps)"
    groups:
      etl-dev:
        patterns:
          - "*"
