/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CompanySearchImport } from './routes/company-search'
import { Route as CompaniesImport } from './routes/companies'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CompanySearchRoute = CompanySearchImport.update({
  id: '/company-search',
  path: '/company-search',
  getParentRoute: () => rootRoute,
} as any)

const CompaniesRoute = CompaniesImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesImport
      parentRoute: typeof rootRoute
    }
    '/company-search': {
      id: '/company-search'
      path: '/company-search'
      fullPath: '/company-search'
      preLoaderRoute: typeof CompanySearchImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/company-search': typeof CompanySearchRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/company-search': typeof CompanySearchRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/company-search': typeof CompanySearchRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/companies' | '/company-search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/companies' | '/company-search'
  id: '__root__' | '/' | '/companies' | '/company-search'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesRoute: typeof CompaniesRoute
  CompanySearchRoute: typeof CompanySearchRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesRoute: CompaniesRoute,
  CompanySearchRoute: CompanySearchRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/companies",
        "/company-search"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/companies": {
      "filePath": "companies.tsx"
    },
    "/company-search": {
      "filePath": "company-search.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
