fail_fast: true # Stop at first failure

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
        files: ^.*\.toml$
      - id: check-yaml
        args: ["--unsafe"]
        files: ^.*\.yml$
      - id: check-added-large-files
        files: ^etl/|^server/
        exclude: >
          (?x)^(
            etl/data/resources/.*\.csv|
            etl/data/municipality_code.csv
          )$
      - id: requirements-txt-fixer
        files: ^etl/requirements.txt$|^server/requirements.txt$
      - id: forbid-new-submodules
        files: ^etl/|^server/
      - id: no-commit-to-branch
        args: ["--branch=main"]
        files: ^etl/|^server/
      - id: detect-private-key
        files: ^etl/|^server/

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--config", "etl/.black.toml"]
        files: ^etl/.*\.py$
      - id: black
        args: ["--config", "server/.black.toml"]
        files: ^server/.*\.py$

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        args: ["--config", "etl/ruff.toml"]
        files: ^etl/.*\.py$
      - id: ruff
        args: ["--config", "server/ruff.toml"]
        files: ^server/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--settings-path", "etl/.isort.cfg"]
        files: ^etl/.*\.py$
      - id: isort
        args: ["--settings-path", "server/.isort.cfg"]
        files: ^server/.*\.py$

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.397
    hooks:
      - id: pyright
        args: ["--project", "etl/pyrightconfig.json"]
        files: ^etl/.*\.py$
      - id: pyright
        args: ["--project", "server/pyrightconfig.json"]
        files: ^server/.*\.py$

  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
      - id: darglint
        args: ["--docstring-style", "google"]
        exclude: ^etl/data/
        files: ^etl/.*\.py$
      - id: darglint
        args: ["--docstring-style", "google"]
        exclude: ^server/data/
        files: ^server/.*\.py$

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: ["--configfile", "etl/bandit.yaml"]
        exclude: ^etl/data/
        files: ^etl/.*\.py$
      - id: bandit
        args: ["--configfile", "server/bandit.yaml"]
        exclude: ^server/data/
        files: ^server/.*\.py$

  - repo: https://github.com/biomejs/pre-commit
    rev: "v1.9.4" # Use the sha / tag you want to point at
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.9.1"]
        files: ^client/.*\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\.(ts|cts|mts)|jsonc?)$
        exclude: ^client/(ignored-folder|node_modules|\.next)/
        args: ["--config-path", "client/biome.json"]

