services:
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/db:/docker-entrypoint-initdb.d

  # etl:
  #   build:
  #     context: ./etl
  #   container_name: etl
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  
  #   Uncomment the following lines of server if you want to run the ETL process and load_data.py manually.
  #   Remember delete images and containers before running load-data.py and after that run the server.
  server:
    build:
      context: ./server
    container_name: fastapi
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      DATABASE_URI: ${DATABASE_URL_DOCKER}
      ENV: ${ENV}
      CHUNK_SIZE: ${CHUNK_SIZE}
      API_URL: ${API_URL}

#  client:
#    build:
#      context: ./client
#    container_name: react
#    depends_on:
#      - db
#      - server
#    volumes:
#      - ./client:/app
#      - /app/node_modules
#      - next_cache:/app/.next
#    ports:
#      - '3000:3000'
#    env_file:
#      - .env
#    environment:
#      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
#      VITE_PORT: "3001"
#      VITE_API_PATH: "/api/v1"
#      ENV: ${ENV}
#
volumes:
  postgres_data:
  next_cache: