services:
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/db:/docker-entrypoint-initdb.d

  # etl:
  #   build:
  #     context: ./etl
  #   container_name: etl
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env

  server:
    build:
      context: ./server
    container_name: fastapi
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  postgres_data:
