services:
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/db:/docker-entrypoint-initdb.d

  # etl:
  #   build:
  #     context: ./etl
  #   container_name: etl
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env

  server:
    build:
      context: ./server
    container_name: fastapi
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

  client:
    build:
      context: ./client
    container_name: vite-react
    volumes:
      # Bind mount to sync file changes between host and container, ro = read only
      - ./client:/app
      # Empty node_modules as Anonymous volume => node_modules is not synced
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      VITE_BACKEND_URL: "http://localhost"
      VITE_PORT: "3001"
      VITE_API_PATH: "/api/v1"
      #restart: "unless-stopped"

volumes:
  postgres_data:
