# Static mappings configuration
#
# This file contains static mappings used for data processing in the ETL pipeline.
# Mappings include translations, identifiers, and standardized codes for
# multi-language and multi-context support. Each section is tailored to a 
# specific type of mapping, such as language codes, type mappings, and authorities.
#

mappings:
  # Default country setting
  default_country:
    fi: "Finland"
    en: "Finland"
    sv: "Finland"

  # Language code mappings
  language_code_mapping:
    fi: "1"  # Finnish
    sv: "2"  # Swedish
    en: "3"  # English

  # Type mappings for statuses in different languages
  type_mapping:
    fi:
      KONK: "Konkurssissa"
      SANE: "Saneerauksessa"
      SELTILA: "Selvitystilassa"
    en:
      KONK: "Bankrupt"
      SANE: "Company re-organisation"
      SELTILA: "Liquidation"
    sv:
      KONK: "I konkurs"
      SANE: "Sanering"
      SELTILA: "I likvidation"

  address_mapping:
    fi:
      1: "Käyntiosoite"
      2: "Postiosoite"
    en:
      1: "Visiting address"
      2: "Postal address"
    sv:
      1: "Besöksadress"
      2: "Postadress"

  source_mapping:
    fi:
      "0": "Yhteinen"
      "1": "Patentti- ja rekisterihallitus"
      "2": "Verohallinto"
      "3": "Yritys- ja yhteisötietojärjestelmä"
    en:
      "0": "Common"
      "1": "Finnish Patent and Registration Office"
      "2": "Tax Administration"
      "3": "Business Information System"
    sv:
      "0": "Gemensam"
      "1": "Patent- och registerstyrelsen"
      "2": "Skatteförvaltningen"
      "3": "Företags- och organisationsdatasystemet"

  rek_kdi_mapping:
    fi:
      "0": "Rekisteröimätön"
      "1": "Rekisterissä"
      "2": "Poistettu rekisteristä"
      "3": "Ei rekisteröity perustaminen"
      "4": "Lakannut"
      "55": "Rekisterissä"
      "99": "Aiheeton rivi"
      "32": "turha (8_32)"
      "35": "Ei katso olevansa alv-velvollinen"
      "80": "Liiketoiminnasta arvonlisäverovelvollinen"
      "82": "Kiinteistön käyttöoikeuden luovuttamisesta"
      "83": "Alkutuottajana ja/tai kuvataiteilijana arvonlisäverovelvollinen"
      "84": "Porotaloudesta arvonlisäverovelvollinen"
      "85": "Ulkomaalainen arvonlisäveroilmoituksenantovelvollinen"
      "86": "Ostajana tai omasta käytöstä arvonlisäverovelvollinen"
      "87": "EU-palvelumyynneistä ilmoituksenantovelvollinen"
      "88": "Taide-esineen myynnistä tai tekijänä arvonlisäverovelvollinen"
      "99": "Aiheeton rivi"
      "P84": "Paliskunnan osakkaana"
      "V80": "Vastuuryhmän jäsenenä"
      "41": "Rekisterissä"
      "42": "Rekisterissä"
      "99": "Aiheeton rivi"
      "32": "Rekisterissä"
    sv:
      "0": "Oregistrerad"
      "1": "Registrerad"
      "2": "Utplånats ur registret"
      "3": "Oregistrerat grundande"
      "4": "Upphört"
      "55": "Registrerad"
      "99": "Onödig rad"
      "32": "Onödig (8_32)"
      "80": "Momsskyldig för rörelseverksamhet"
      "82": "För överlåtelse av nyttjanderätten till en fastighet"
      "83": "Momsskyldig som primärproducent och/eller bildkonstnär"
      "84": "Momsskyldig för renhushållning"
      "85": "Utländsk momsdeklarationsskyldig"
      "86": "Momsskyldig som köpare eller för eget bruk"
      "87": "Deklarationsskyldig för försäljning av tjänster inom EU"
      "88": "Momsskyldig som säljare av eller upphovsman till konstverk"
      "99": "Onödig rad"
      "P84": "Momsskyldig som medlem i renbeteslag"
      "V80": "Momsskyldig som medlem i ansvarsgruppen"
      "41": "Registrerad"
      "42": "Registrerad"
      "99": "Onödig rad"
      "32": "Registrerad"
    en:
      "0": "Unregistered"
      "1": "Registered"
      "2": "Removed from register"
      "3": "Start-up not registered"
      "4": "Ceased"
      "55": "Registered"
      "99": "Incorrect line"
      "80": "VAT-liable for business activity"
      "82": "VAT-obliged for the transfer of rights to use immovable property"
      "83": "VAT-liable for agriculture and forestry"
      "84": "VAT-liable for reindeer husbandry"
      "85": "Registration only for Notification Duty as a foreign company"
      "86": "VAT liable as a buyer or on self-supply"
      "87": "Party subject to VAT notification duty for supply of services in the EU"
      "88": "Liable for VAT for supply of / as a creator of works of art"
      "99": "Incorrect line"
      "P84": "Co-owner in a reindeer grazing association"
      "V80": "Member of liability group"
      "41": "Registered"
      "42": "Registered"
      "99": "Incorrect line"
      "32": "Registered"

  status_mapping:
    fi:
      "1": "Vireillä"
      "2": "Voimassa"
      "5": "Yritystunnus poistettu käytöstä"
    sv:
      "1": "Mottagits"
      "2": "Giltigt"
      "5": "Upphävt företagsnummer"
    en:
      "1": "Pending"
      "2": "Valid"
      "5": "Business ID invalidated"

  name_type_mapping:
    fi:
      "1": "Toiminimi"
      "2": "Rinnakkaistoiminimi"
      "3": "Aputoiminimi"
      "4": "Aputoiminimen käännös"
    en:
      "1": "Company name"
      "2": "Parallel company name"
      "3": "Auxiliary company name"
      "4": "Translation of the auxiliary company name"
    sv:
      "1": "Firma"
      "2": "Parallellfirma"
      "3": "Bifirma"
      "4": "Översättning av bifirma"

  register_mapping:
    fi:
      "1": "Kaupparekisteri"
      "2": "Säätiörekisteri"
      "3": "Yhdistysrekisteri"
      "4": "Verohallinnon perustiedot"
      "5": "Ennakkoperintärekisteri"
      "6": "Arvonlisäverovelvollisuus"
      "7": "Työnantajarekisteri"
      "8": "Vakuutusmaksuverovelvollisten rekisteri"
    en:
      "1": "Trade register"
      "2": "Foundation register"
      "3": "Register of Associations"
      "4": "Tax Administration"
      "5": "Prepayment register"
      "6": "Value added tax-liability"
      "7": "Employer register"
      "8": "Register for insurance premium taxpayers"
    sv:
      "1": "Handelsregistret"
      "2": "Stiftelseregistret"
      "3": "Föreningsregistret"
      "4": "Skatteförvaltningens basuppgifter"
      "5": "Förskottsuppbördsregistret"
      "6": "Momsskyldighet"
      "7": "Arbetsgivarregistret"
      "8": "Registret över försäkringspremieskattskyldiga"

  authority_mapping:
    fi:
      "1": "Verohallinto"
      "2": "Patentti- ja rekisterihallitus"
      "3": "Väestörekisterikeskus"
    en:
      "1": "Tax Administration"
      "2": "Finnish Patent and Registration Office"
      "3": "Finnish Population Register Centre"
    sv:
      "1": "Skatteförvaltningen"
      "2": "Patent- och registerstyrelsen"
      "3": "Befolkningsregistercentralen"
