columns:
  businessId:
    type: string
    nullable: false
  languageCode:
    type: string
    nullable: false
    mappings:
      fi: "Finnish"
      en: "English"
      sv: "Swedish"
  description:
    type: string
    nullable: true

options:
  remove_duplicates: true
  validate_column_names: true
