columns:
  businessId:
    type: string
    nullable: false
  type:
    type: string
    nullable: false
    mappings:
      2: "Housing Corporation"
      10: "Mutual Real Estate Limited Company"
      16: "Limited Company"
      17: "Public Limited Company"
  description:
    type: string
    nullable: true

options:
  remove_duplicates: true
  validate_column_names: true
