columns:
  businessId:
    type: string
    nullable: false
  registrationDate:
    type: date
    nullable: true
  tradeRegisterStatus:
    type: string
    nullable: true
    mappings:
      Registered: "Registered"
      Not Registered: "Not Registered"
  status:
    type: string
    nullable: true
    mappings:
      Valid: "Active"
      Invalid: "Inactive"
  registrationDateCompany:
    type: date
    nullable: true
  endDate:
    type: date
    nullable: true
  lastModified:
    type: date
    nullable: true

options:
  remove_duplicates: true
  validate_column_names: true
  default_date_format: "%Y-%m-%d"
