columns:
  businessId:
    type: string
    nullable: false
  type:
    type: string
    nullable: false
    mappings:
      Bankrupt: "Bankruptcy"
      Liquidation: "Liquidation"
  registrationDate:
    type: date
    nullable: true
  endDate:
    type: date
    nullable: true
  source:
    type: string
    nullable: true

options:
  remove_duplicates: true
  validate_column_names: true
  default_date_format: "%Y-%m-%d"
