columns:
  businessId:
    type: string
    nullable: false
  type:
    type: string
    nullable: false
    mappings:
      2: "Housing Corporation"
      10: "Mutual Real Estate Limited Company"
      16: "Limited Company"
      17: "Public Limited Company"
  registrationDate:
    type: date
    nullable: true
  endDate:
    type: date
    nullable: true
  version:
    type: integer
    nullable: true
  source:
    type: string
    nullable: true

options:
  remove_duplicates: true
  validate_column_names: true
  default_date_format: "%Y-%m-%d"
