columns:
  businessId:
    type: string
    nullable: false
  postCode:
    type: string
    nullable: true
  city:
    type: string
    nullable: true
  active:
    type: boolean
    nullable: true
  languageCode:
    type: string
    nullable: false
    mappings:
      en: "English"
      fi: "Finnish"
      sv: "Swedish"
  municipalityCode:
    type: string
    nullable: true

options:
  remove_duplicates: true
  validate_column_names: true
