# List of supported cities with metadata
cities:
  - name: NOKIA
    metadata:
      population: 33000
      region: "Pirkanmaa"
  - name: TAMPERE
    metadata:
      population: 238000
      region: "Pirkanmaa"

# Directory structure for processing city data
directory_structure:
  city_dir: "etl/data/processed/{city}"
  filtered_dir: "etl/data/processed/{city}/filtered"
  split_dir: "etl/data/processed/{city}/splitted"
