# List of supported cities
cities:
  - NOKIA
  - TAMPERE

# Metadata for cities
metadata:
  NOKIA:
    population: 33000
    region: "Pirkanmaa"
  TAMPERE:
    population: 238000
    region: "Pirkanmaa"

# Directory structure for processing city data
directory_structure:
  city_dir: "etl/data/processed/{city}"
  filtered_dir: "etl/data/processed/{city}/filtered"
  split_dir: "etl/data/processed/{city}/splitted"
