# Directory Configuration

# Directory structure for various stages of the ETL process
directory_structure:
  # Directory for raw data files before processing
  raw_dir: etl/data/1_raw/
  # Directory for data extracted and pre-processed from raw files
  extracted_dir: etl/data/2_extracted/
  # Directory for fully processed data ready for analysis or export
  processed_dir: etl/data/3_processed/
  # Directory for storing log files generated during ETL processes
  logs_dir: etl/data/logs/
  # Path to base schema files used for validation or structure definition
  base_schema_path: etl/config/schemas/
  # Path to the database schema file for migrations or reference
  db_schema_path: server/db/schema.sql

# Path to the mappings file that defines relationships or configurations
mappings_file: "./config/mappings.yml"

# Supported languages for processing and translation
languages:
  # English language configuration
  english: "en"
  # Finnish language configuration
  finnish: "fi"
  # Swedish language configuration
  swedish: "sv"

# Additional paths for configuration and mappings
mappings_path: etl/config/mappings/mappings.yml
toimi_files_path: etl/data/1_raw/mappings

# The name of the primary input file
file_name: companies.zip
