# Entity Configurations
#
# This file defines the entities processed in the ETL pipeline. Each entity 
# represents a table or dataset to be extracted, transformed, and loaded. 
# For each entity, it specifies the name, corresponding database table, 
# and the extractor function to be used.
#
# Key Sections:
# - `entities`: Lists all the entities with their metadata, including:
#   - `name`: The name of the entity.
#   - `table`: The target database table.
#   - `extractor`: The function used to process the entity.
#   - `validation`: Contains schema information for column validation.
entities:
  - name: "companies"
    table: "companies"
    specific_columns: ["registration_date", "end_date", "last_modified"]
    extractor: "etl.pipeline.extract.companies_extractor.CompaniesExtractor"
    validation:
      columns:
        business_id: "VARCHAR(20)"
        website: "VARCHAR(255)"
        registration_date: "DATE"
        trade_register_status: "VARCHAR(50)"
        status: "VARCHAR(50)"
        end_date: "DATE"
        last_modified: "DATE"
      required:
        - business_id
      constraints:
        - PRIMARY KEY (business_id)

  - name: "names"
    table: "names"
    extractor: "etl.pipeline.extract.names_extractor.NamesExtractor"
    validation:
      columns:
        id: "SERIAL"
        business_id: "VARCHAR(20)"
        name: "VARCHAR(255)"
        type: "VARCHAR(50)"
        registration_date: "DATE"
        end_date: "DATE"
        version: "INT"
        source: "VARCHAR(255)"
      required:
        - business_id
        - name

  - name: "addresses"
    table: "addresses"
    specific_columns: ["post_code", "apartment_number", "building_number", "post_office_box"]
    extractor: "etl.pipeline.extract.addresses_extractor.AddressesExtractor"
    validation:
      columns:
        id: "SERIAL"
        business_id: "VARCHAR(20)"
        type: "VARCHAR(50)"
        street: "VARCHAR(255)"
        building_number: "VARCHAR(50)"
        entrance: "VARCHAR(50)"
        apartment_number: "VARCHAR(50)"
        apartment_id_suffix: "VARCHAR(50)"
        post_code: "VARCHAR(10)"
        post_office_box: "VARCHAR(50)"
        co: "VARCHAR(255)"
        country: "VARCHAR(50)"
        free_address_line: "VARCHAR(255)"
        registration_date: "DATE"
        source: "VARCHAR(255)"
      required:
        - post_code
        - country

  - name: "main_business_lines"
    table: "main_business_lines"
    extractor: "etl.pipeline.extract.main_business_lines_extractor.MainBusinessLinesExtractor"
    validation:
      columns:
        id: "SERIAL"
        business_id: "VARCHAR(20)"
        type: "VARCHAR(255)"
        type_code_set: "VARCHAR(50)"
        registration_date: "DATE"
        source: "VARCHAR(255)"
      required:
        - business_id
        - type

  - name: "registered_entries"
    table: "registered_entries"
    specific_columns: ["registration_date", "end_date"]
    extractor: "etl.pipeline.extract.registered_entries_extractor.RegisteredEntriesExtractor"
    validation:
      columns:
        id: "SERIAL"
        business_id: "VARCHAR(20)"
        type: "VARCHAR(10)"
        registration_date: "DATE"
        end_date: "DATE"
        register: "VARCHAR(255)"
        authority: "VARCHAR(255)"
      required:
        - business_id
        - type

  - name: "company_forms"
    table: "company_forms"
    extractor: "etl.pipeline.extract.company_forms_extractor.CompanyFormsExtractor"
    validation:
      columns:
        id: "SERIAL"
        business_id: "VARCHAR(20)"
        type: "INT"
        registration_date: "DATE"
        end_date: "DATE"
        version: "INT"
        source: "VARCHAR(255)"
      required:
        - business_id
        - type
  - name: "post_offices"
    table: "post_offices"
    specific_columns: ["post_code"]
    extractor: "etl.pipeline.extract.post_offices_extractor.PostOfficesExtractor"
    validation:
      columns:
        id: "SERIAL"
        business_id: "VARCHAR(20)"
        post_code: "VARCHAR(10)"
        city: "VARCHAR(100)"
        municipality_code: "INT"
        active: "BOOLEAN"
      required:
        - post_code

  - name: "company_situations"
    table: "company_situations"
    extractor: "etl.pipeline.extract.company_situations_extractor.CompanySituationsExtractor"
    validation:
      columns:
        id: "SERIAL"
        business_id: "VARCHAR(20)"
        type: "VARCHAR(100)"
        registration_date: "DATE"
        end_date: "DATE"
        source: "VARCHAR(255)"
      required:
        - business_id
        - type
        - registration_date
