# Entity Configurations
#
# This file defines the entities processed in the ETL pipeline. Each entity 
# represents a table or dataset to be extracted, transformed, and loaded. 
# For each entity, it specifies the name, corresponding database table, 
# and the extractor function to be used.
#
# Key Sections:
# - `entities`: Lists all the entities with their metadata, including:
#   - `name`: The name of the entity.
#   - `table`: The target database table.
#   - `extractor`: The function used to process the entity.

entities:
  - name: "companies"
    table: "companies"
    extractor: "etl.pipeline.extract.companies_extractor.CompaniesExtractor"
  - name: "names"
    table: "names"
    extractor: "etl.pipeline.extract.names_extractor.NamesExtractor"
  - name: "addresses"
    table: "addresses"
    extractor: "etl.pipeline.extract.addresses_extractor.AddressesExtractor"
  - name: "main_business_lines"
    table: "main_business_lines"
    extractor: "etl.pipeline.extract.main_business_lines_extractor.MainBusinessLinesExtractor"
  - name: "registered_entries"
    table: "registered_entries"
    extractor: "etl.pipeline.extract.registered_entries_extractor.RegisteredEntriesExtractor"
  - name: "registered_entry_descriptions"
    table: "registered_entry_descriptions"
    extractor: "etl.pipeline.extract.registered_entry_descriptions_extractor.RegisteredEntryDescriptionsExtractor"
  - name: "company_forms"
    table: "company_forms"
    extractor: "etl.pipeline.extract.company_forms_extractor.CompanyFormsExtractor"
  - name: "company_form_descriptions"
    table: "company_form_descriptions"
    extractor: "etl.pipeline.extract.company_form_descriptions_extractor.CompanyFormDescriptionsExtractor"
  - name: "business_line_descriptions"
    table: "business_line_descriptions"
    extractor: "etl.pipeline.extract.business_line_descriptions_extractor.BusinessLineDescriptionsExtractor"
  - name: "post_offices"
    table: "post_offices"
    extractor: "etl.pipeline.extract.post_offices_extractor.PostOfficesExtractor"
  - name: "company_situations"
    table: "company_situations"
    extractor: "etl.pipeline.extract.company_situations_extractor.CompanySituationsExtractor"
