# etl.yml
url_templates:
  base: 'https://avoindata.prh.fi/opendata-ytj-api/v3/'
  endpoints:
    all_companies: "all_companies"
    description: "description?code={code}&lang={lang}"

chunk_size: 1000

languages:
  finnish: "fi"
  english: "en"
  swedish: "sv"

codes:
  - "TOIMI"
  - "TOIMI2"
  - "TOIMI3"

entities:
  - name: "companies"
    table: "companies"
    extractor: "etl.pipeline.extract.extract_companies.extract_companies"
  - name: "names"
    table: "names"
    extractor: "etl.pipeline.extract.extract_names.extract_names"
  - name: "addresses"
    table: "addresses"
    extractor: "etl.pipeline.extract.extract_addresses.extract_addresses"
  - name: "main_business_lines"
    table: "main_business_lines"
    extractor: "etl.pipeline.extract.extract_main_business_lines.extract_main_business_lines"
  - name: "registered_entries"
    table: "registered_entries"
    extractor: "etl.pipeline.extract.extract_registered_entries.extract_registered_entries"
  - name: "registered_entry_descriptions"
    table: "registered_entry_descriptions"
    extractor: "etl.pipeline.extract.extract_registered_entry_descriptions.extract_registered_entry_descriptions"
  - name: "company_forms"
    table: "company_forms"
    extractor: "etl.pipeline.extract.extract_company_forms.extract_company_forms"
  - name: "company_form_descriptions"
    table: "company_form_descriptions"
    extractor: "etl.pipeline.extract.extract_company_form_descriptions.extract_company_form_descriptions"
  - name: "business_line_descriptions"
    table: "business_line_descriptions"
    extractor: "etl.pipeline.extract.extract_business_line_descriptions.extract_business_line_descriptions"
  - name: "post_offices"
    table: "post_offices"
    extractor: "etl.pipeline.extract.extract_post_offices.extract_post_offices"
  - name: "company_situations"
    table: "company_situations"
    extractor: "etl.pipeline.extract.extract_company_situations.extract_company_situations"
