version: 1
disable_existing_loggers: False
formatters:
  standard:
    format: '%(asctime)s - %(levelname)s - %(message)s'
handlers:
  console:
    level: INFO
    class: logging.StreamHandler
    formatter: standard
  file:
    level: INFO
    class: logging.FileHandler
    filename: etl.log
    formatter: standard
loggers:
  '':
    handlers: ['console', 'file']
    level: INFO
    propagate: True
  etl:
    handlers: ['console', 'file']
    level: INFO
    propagate: False
