name: Run Change Detection

on:
  workflow_dispatch:

jobs:
  change-detection:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
      ETL_TASK_DEF: ${{ secrets.ETL_TASK_DEF }}
      ETL_CONTAINER_NAME: ${{ secrets.ETL_CONTAINER_NAME }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Run Change Detection ECS Task (fire-and-forget)
        run: |
          aws ecs run-task \
            --cluster $ECS_CLUSTER \
            --task-definition $ETL_TASK_DEF \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[${{ secrets.SUBNET_ID }}],securityGroups=[${{ secrets.SECURITY_GROUP_ID }}],assignPublicIp=ENABLED}" \
            --overrides '{"containerOverrides":[{"name":"${{ env.ETL_CONTAINER_NAME }}","command":["python","etl/utils/change_detection.py"]}]}'
          echo "Change Detection ECS task started. Monitor progress in AWS ECS/CloudWatch." 