name: Server Test

on:
  # Only trigger manually - removed automatic push trigger
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          cd server
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Initialize test database
        env:
          PGPASSWORD: postgres
        run: |
          cd server
          psql -h localhost -U postgres -d testdb -f db/schema.sql
          psql -h localhost -U postgres -d testdb -f db/test_data.sql

      - name: Test with pytest
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
          DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/testdb
          ENVIRONMENT: test
          BYPASS_RATE_LIMIT: "true"
          GITHUB_ACTIONS: "true"
        run: |
          cd server
          python -m pytest --cov=backend --cov-report=xml tests/
          
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./server/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false 